pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
                echo "Build Stage"
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
                echo "mvn test"
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                echo "Delivery stage"
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
